### PR TITLE
Support cloud statistics plugin

### PR DESCRIPTION
**Pull request by ArchangelSDY**
This PR added support for [Cloud Statistics Plugin](https://wiki.jenkins-ci.org/display/JENKINS/Cloud+Statistics+Plugin) as requested by [JENKINS-42799](https://issues.jenkins-ci.org/browse/JENKINS-42799).

Cloud Statistics Plugin aggregates cloud provisioning activities and has about 800 downloads last month. By integrating with this plugin I think it may be useful for user to track their Azure cloud agents.

Here is a screenshot:

image

### CODE REVIEW

**Comment by ArchangelSDY** [comment]
I also did some tests in error cases. Maybe we can use it to display our error messages.

image

**Comment by clguimanMSFT** [comment]
AdministrativeMonitor should be used for displaying error messages: http://javadoc.jenkins.io/hudson/model/AdministrativeMonitor.html

**Comment by clguimanMSFT** [comment]
Please include a reference to the Jira item in the commit message

**Comment by ArchangelSDY** [comment]
Thanks! I'll have a look at it.

**Pull request merged**
