### PR TITLE
Fix Node stays suspended after node is started

### PR DESCRIPTION
**Pull request by lukaszun**
Fixes https://github.com/jenkinsci/azure-vm-agents-plugin/issues/238

### CODE REVIEW

**Comment by gavinfish** [comment]
@lukaszun Thanks for your PR here. Do you verify this can migrate the JENKINS-54776 issue?

**Comment by lukaszun** [comment]
@gavinfish I've tested this fix for 54776 issue and it mitigates this problem.

**Comment by gavinfish** [comment]
This change makes sense to me. But I cannot steadily test it since the 54766 issue is not easily reproduced on my side. So I want to provide a preview version on GitHub for others who is willing to test it.

**Comment by lukaszun** [comment]
OK, shall I fix conflicts by myself or you would fix it?

**Comment by gavinfish** [comment]
Conflicts fixed.

**Comment by gavinfish** [comment]
One more question for you @lukaszun , the new code here will not wait for the connection finished. I think it may cause problem when master sending jobs to agent if the connection has not been finished at that time. Why not use `Future.get()` here?

**Comment by lukaszun** [comment]
I didn't investigate that deeply but for some reason this Feature is not getting resolved at all, so with ".get" code hangs forever here

**Comment by lukaszun** [comment]
@gavinfish something wrong happend after your conflict resolution commit -> could you fix it?

**Comment by mattydebie** [comment]
I can confirm that starting from 896804c11d6f888db72f944d1663e2f175afa6f5 and applying this fix  (like @lukaszun 's branch) works, but using the preview release v0.9.1-PREVIEW does not.

**Comment by gavinfish** [comment]
@mattydebie what is the error message then?

**Comment by mattydebie** [comment]
It's not really an error, everything works fine up until starting the vm.
Below are the logs for a *deallocated vm*, which was put as *stopped* by the idle timeout.
```
FINE    c.m.azure.vmagent.AzureVMCloud#getAzureAgentTemplate: AzureVMCloud: getAzureAgentTemplate: Retrieving agent template with label chef2
FINE    c.m.azure.vmagent.AzureVMCloud#getAzureAgentTemplate: AzureVMCloud: getAzureAgentTemplate: Found agent template ubuntu-test
FINE    c.m.azure.vmagent.AzureVMCloud#getAzureAgentTemplate: AzureVMCloud: getAzureAgentTemplate: Found agent template test-jenkins-ubuntu
FINE    c.m.azure.vmagent.AzureVMCloud#getAzureAgentTemplate: AzureVMCloud: getAzureAgentTemplate: test-jenkins-ubuntu matches!
INFO    c.m.azure.vmagent.AzureVMCloud#provision: AzureVMCloud: provision: start for label chef2 workLoad 1
FINE    c.m.azure.vmagent.AzureVMCloud#getAzureAgentTemplate: AzureVMCloud: getAzureAgentTemplate: Retrieving agent template with label chef2
FINE    c.m.azure.vmagent.AzureVMCloud#getAzureAgentTemplate: AzureVMCloud: getAzureAgentTemplate: Found agent template ubuntu-test
FINE    c.m.azure.vmagent.AzureVMCloud#getAzureAgentTemplate: AzureVMCloud: getAzureAgentTemplate: Found agent template test-jenkins-ubuntu
FINE    c.m.azure.vmagent.AzureVMCloud#getAzureAgentTemplate: AzureVMCloud: getAzureAgentTemplate: test-jenkins-ubuntu matches!
INFO    c.m.azure.vmagent.AzureVMCloud#provision: AzureVMCloud: provision: checking for node reuse options
INFO    c.m.azure.vmagent.AzureVMCloud#provision: AzureVMCloud: provision: agent computer eligible for reuse test-jenkins-ubuntu9b87b0
INFO    c.m.a.v.AzureVMManagementServiceDelegate#virtualMachineExists: AzureVMManagementServiceDelegate: virtualMachineExists: check for test-jenkins-ubuntu9b87b0
INFO    c.m.a.v.AzureVMManagementServiceDelegate#virtualMachineExists: AzureVMManagementServiceDelegate: virtualMachineExists: test-jenkins-ubuntu9b87b0 exists
INFO    c.m.azure.vmagent.AzureVMCloud#provision: AzureVMCloud: provision: asynchronous provision finished, returning 1 planned node(s)
INFO    c.m.azure.vmagent.AzureVMCloud$2#call: Found existing node, starting VM test-jenkins-ubuntu9b87b0
INFO    c.m.a.v.AzureVMManagementServiceDelegate#startVirtualMachine: AzureVMManagementServiceDelegate: startVirtualMachine: test-jenkins-ubuntu9b87b0
FINE    hudson.model.AsyncPeriodicWork$1#run: Started Azure VM Agents Clean Task
FINE    c.m.a.v.AzureVMAgentCleanUpTask#execute: AzureVMAgentCleanUpTask: execute: start
FINE    c.m.a.v.AzureVMAgentCleanUpTask#execute: AzureVMAgentCleanUpTask: execute: Running clean with 5 minute timeout
FINE    c.m.a.v.AzureVMAgentCleanUpTask#cleanVMs: AzureVMAgentCleanUpTask: cleanVMs: node test-jenkins-ubuntu9b87b0 blocked to cleanup
FINE    c.m.a.v.AzureVMAgentCleanUpTask#cleanDeployments: AzureVMAgentCleanUpTask: cleanDeployments: Cleaning deployments
FINE    c.m.a.v.AzureVMAgentCleanUpTask#cleanDeployments: AzureVMAgentCleanUpTask: cleanDeployments: Checking deployment test-jenkins-ubuntu0416091918126
FINE    c.m.a.v.AzureVMAgentCleanUpTask#cleanDeployments: AzureVMAgentCleanUpTask: cleanDeployments: Deployment created on 4/16/19 9:21 AM
FINE    c.m.a.v.AzureVMAgentCleanUpTask#cleanDeployments: AzureVMAgentCleanUpTask: cleanDeployments: Deployment newer than timeout, keeping
FINE    c.m.a.v.AzureVMAgentCleanUpTask#cleanDeployments: AzureVMAgentCleanUpTask: cleanDeployments: Done cleaning deployments
FINE    c.m.a.v.AzureVMAgentCleanUpTask#execute: AzureVMAgentCleanUpTask: execute: end
FINE    hudson.model.AsyncPeriodicWork$1#run: Finished Azure VM Agents Clean Task. 1,489 ms
```
There it just hangs, and only does the cleanup

**Comment by mattydebie** [comment]
@gavinfish Was the log any help?

**Comment by lukaszun** [comment]
@gavinfish are there any problems with this PR that it hasn't been merged yet?

**Comment by gavinfish** [comment]
Forcing reconnect is fine to me, but I think the `get()` should still be here. We just set the `azureComputer.setAcceptingTasks(true);` below the code which may accept task before the agent is online.

**Comment by nirud** [comment]
Hello,

i am having the same problem and i did some digging. The main problem is that the get() call is inside the synchronized(agentNode) block. 

The branch-api-plugin plugin (in the WorkspaceLocatorImpl.java line 533) also tries to synchronized over the agentNode to do some workspace cleaning **before** the node goes online and the AzureVMCloud.java class is only releasing the lock **after** the node has gone online.

I verified it by closing the syncronized block before the Future.get() call and then it worked. But i am not sure if this works with the rest of the code, because i think then it may be possible to provision the same node twice.

I would create a PR if somebody could help me what locking strategy would work with the rest of the code without blocking the agentNode.

**Comment by Minreaux** [comment]
Any update on this? This issue is still present on Jenkins v2.387.1 LTS using Azure VM Agents v825.v470cb_9e7361a_

**Comment by nirud** [comment]
The problem has been solved for me with https://github.com/jenkinsci/azure-vm-agents-plugin/pull/185 
and it works here in 825.v470cb_9e7361a_ .

If is happens again it is probably due to another reason than i described above.

**Pull request closed without merging**
