### PR TITLE
Incrementalified.

### PR DESCRIPTION
**Pull request by timja**
See:
https://github.com/jenkinsci/incrementals-tools

I would like to be able to get incremental builds for PRs here to making testing of changes easier for machines other than my own

### CODE REVIEW

**Comment by timja** [comment]
@gavinfish small one for you

**Comment by gavinfish** [comment]
@timja A good suggestion here. I need more time to read JEP-305, and figure out whether this will affect our release process.

**Comment by timja** [comment]
assuming you use the maven plugin to release for you it won't affect it at all.
The plugin-pom and the maven extension make it seamless

and especially given this is a single module project its even simpler

**Comment by timja** [comment]
This would mean a build automatically made available on github for PRs like this so you don't need to make a preview release:
https://github.com/jenkinsci/azure-vm-agents-plugin/pull/141

also available via the install-plugins.sh script for docker and for other plugins to depend on

**Comment by gavinfish** [comment]
One more unrelated question here @timja , I want to release a new version which might have broken changes for users. So I want to let them read about  migration documentation first. What is the suggested way to achieve this?

**Comment by timja** [comment]
Add this:
https://wiki.jenkins.io/display/JENKINS/Marking+a+new+plugin+version+as+incompatible+with+older+versions
```
<hpi.compatibleSinceVersion>0.10</hpi.compatibleSinceVersion>
```

**Comment by gavinfish** [comment]
> Add this:
> https://wiki.jenkins.io/display/JENKINS/Marking+a+new+plugin+version+as+incompatible+with+older+versions
> 
> ```
> <hpi.compatibleSinceVersion>0.10</hpi.compatibleSinceVersion>
> ```

Thanks a lot!

**Pull request merged**
