### PR TITLE
Fix JENKINS 55935 issue

### PR DESCRIPTION
**Pull request by gavinfish**
Prevent unnecessary exceptions to avoid jenkins error pages. https://issues.jenkins-ci.org/browse/JENKINS-55935

### CODE REVIEW

**Comment by jsoref** [comment]
This will handle the most basic case, but it won't handle the more general case of "something but not valid".

**Comment by jsoref** [comment]
(I'm not really sure what that would look like, we don't really use Azure, although I suspect I have some credits...)

**Comment by gavinfish** [comment]
https://github.com/jenkinsci/azure-vm-agents-plugin/blob/3ddb34b613a268c6cce55739c48409b6f8b34a01/src/main/java/com/microsoft/azure/vmagent/AzureVMAgentTemplate.java#L1095-L1096 will take care of invalid ids.

**Comment by jsoref** [comment]
ok :-)

**Pull request merged**
