### PR TITLE
Rename slave.jar

### PR DESCRIPTION
**Pull request by res0nance**
Saw this while looking through the code

### CODE REVIEW

**Comment by gavinfish** [comment]
What is the purpose of this change?

**Comment by res0nance** [comment]
To remove the old slave naming and use the remoting / agent naming convention

**Comment by gavinfish** [comment]
I mean is there any documentation for this change? Is there any benefit for it expect the renaming?

**Comment by res0nance** [comment]
Nope, no benefit other than aligning with the rest of jenkins.

**Comment by gavinfish** [comment]
I have no idea about this naming rule here. Any helpful links?
I have also just searched across GitHub, and it seems `slave.jar` is still active in [windows-slaves-plugin](https://github.com/jenkinsci/windows-slaves-plugin/blob/9ad8c2a32241c70ec00fe25df36a90be5ee20632/src/main/java/hudson/os/windows/ManagedWindowsServiceLauncher.java#L468), [maven-plugin](https://github.com/jenkinsci/maven-plugin/blob/7ac83fa85fda0c4d1d02663059644f0655823879/src/test/java/hudson/maven/MavenJenkinsRule.java#L45) , etc.

**Comment by res0nance** [comment]
https://issues.jenkins-ci.org/browse/JENKINS-42816

**Comment by gavinfish** [comment]
Thanks for contribution and sharing.

**Pull request merged**
