### PR TITLE
Make AzureVMAgentTemplate Image Fields Mutable

### PR DESCRIPTION
**Pull request by dave-tucker**
This allows for image fields to be updated using groovy.
Our use case for this is to automate the promotion of our custom worker
images vs. having to use the UI to make updates.

Signed-off-by: Dave Tucker <dave@dtucker.co.uk>

### CODE REVIEW

**Comment by zackliu** [comment]
The change is acceptable. But, you can also use Builder functions to achieve this now

**Comment by dave-tucker** [comment]
@zackliu Thanks. I couldn't work out how to update *existing* items using the Builder functions.

Here's a sketch of what my Groovy function would look like:
```groovy
def updateAzureImage(String a, String b -> {
    def instance = Jenkins.getInstance()
    def cloud = instance.clouds.getByName('AzureVMAgents')
    def templates = cloud.getVmTemplates()
    templates.each{t ->
        if (t.getTemplateName() == a) {
            t.setImageId(b)
        }
    }
}
```

Our idea is to call `updateAzureImage` in a Pipeline to promote a new Packer Image

**Comment by akomakom** [comment]
@zackliu any thoughts? I have the same use case as @dave-tucker (publishing new images regularly) and just discovered that the fields are final.

**Comment by akomakom** [comment]
Ugly workaround while running on the official release (setting a final field):
```groovy
import java.lang.reflect.*
  
def setFinalValue(def obj, def fieldName, def value) {
  	Field field = obj.class.getDeclaredField(fieldName)
  
	Field modifiersField = Field.class.getDeclaredField("modifiers")
        modifiersField.setAccessible(true)
        modifiersField.setInt(field, field.getModifiers() & ~Modifier.FINAL)

        Field fieldType = Field.getDeclaredField("type")
        fieldType.setAccessible(true)
        fieldType.set(field, String.class)

        field.setAccessible(true)
        field.set(obj, value)
}

// get the appropriate cloud, then:
def template = cloud.vmTemplates.find{ /* some criteria */ }
setFinalValue(template, 'imageId', 'SOME NEW IMAGE ID VALUE')
```
This actually works.
  
Code borrowed from https://gist.github.com/pditommaso/263721865d84dee6ebaf

**Comment by gavinfish** [comment]
I think this is a design decision here, a template should not be changed once it has been created since it may be used in lots of places. You can copy and change some variables for a template by using `AzureVMTemplateBuilder(AzureVMAgentTemplate template)` constructor. If you are sure you want to change an existing template, you can use reflection to do that.

**Comment by akomakom** [comment]
@gavinfish the need to change an existing template *may* be a common use-case (or not).  It seems to fit nicely into the CD mindset: 
1. rebuild image (frequently, eg on code/deps change).
1. update Jenkins to use the new image.  

Azure (and AWS) have no concept of a symlink/alias like maven's SNAPSHOT, so I don't see a better way.  In our implementation, the above happens 5+ times per day.  

If many people have to invent the aforementioned reflection hack, then perhaps it would make sense to make it easier.  If it's just @dave-tucker and me, then perhaps not.

**Comment by dave-tucker** [comment]
Closing as we worked around this by rebuilding the cloud with new templates instead of mutating the templates in place.

**Pull request closed without merging**
