### PR TITLE
Support SSH Config in template configuration

### LINKED ISSUE #356: Port forwarding should be supported in SSH connection method
### What feature do you want to see added?

This would enable cost-free on-demand VPN-like behavior, for example, the equivalent of:

`ssh -R8080:SOME_SERVER_LOCAL_TO_MASTER_NETWORK:8080 AZURE_VM`  
and `/etc/hosts` in the build agent image:
`127.0.1.1 localhost SOME_SERVER_LOCAL_TO_MASTER_NETWORK`

Now any jenkins build host that is created by this plugin can access a local resource without the overhead of setting up an always-on VPN.  Jsch supports this both [explicitly](http://www.jcraft.com/jsch/examples/PortForwardingR.java.html) and via [reading an openssh config file](http://www.jcraft.com/jsch/examples/OpenSSHConfig.java.html).

I can see two ways of achieving this:
1. Adding more entry fields to the configureClouds interface.  For example:
  * Add remote SSH port forwarding, port/host/port (add/delete row)
  * Enter raw SSH command-line arguments (single text box)
2. Adding a **read openssh config file** checkbox to the configureClouds interface.  Then use wildcard matching in config file

Thoughts?

### Upstream changes

_No response_

### PR DESCRIPTION
**Pull request by akomakom**
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

Allow openssh style configuration overrides in Azure VM template configuration.  
See #356 for rationale.  For example, this allows SSH Port Forwarding rules.

Fixes #356

image

### CODE REVIEW

**Comment by akomakom** [comment]
FYI @timja

**Comment by timja** [comment]
Weird the last version failed for compilation issues, I'm not around this week much but I'll try get to it, apologies for missing this

**Review by timja — APPROVED** [review]
Apologies for the delay, I've cleaned it up and I've tested it as far as the breakpoint getting hit with the right value.

**Comment by akomakom** [comment]
FYI, my initial testing of the released version suggests that it breaks template verification with an NPE:

```
Apr 21, 2023 4:47:19 PM INFO com.microsoft.azure.vmagent.AzureVMAgentTemplate$DescriptorImpl doVerifyConfiguration
Verify configuration:
	resourceGroupName: XXXX;
	templateName: azure-slave;
	labels: xxxx;
	location: XXXX;
	virtualMachineSize: Standard_A0;
	storageAccountName: XXXXX;
	noOfParallelJobs: 1;
	imageTopLevelType: advanced;
	builtInImage: Ubuntu 20.04 LTS;
	image: /subscriptions/XXXX;
	osType: Linux;
	id: ;
	publisher: ;
	offer: ;
	sku: ;
	version: latest;
	agentLaunchMethod: SSH;
	initScript: ;
	credentialsId: XXXX;
	virtualNetworkName: XXXX;
	virtualNetworkResourceGroupName: XXXX;
	subnetName: XXXX;
	privateIP: false;
	nsgName: XXXX;
	jvmOptions: ;
	galleryName: 
	galleryImageDefinition: 
	galleryImageVersion: 
	galleryResourceGroup: 
	gallerySubscriptionId: 
	sshConfig: null
Apr 21, 2023 4:47:19 PM SEVERE com.microsoft.azure.vmagent.AzureVMManagementServiceDelegate verifyVirtualMachineImage
Invalid virtual machine image
java.lang.NullPointerException
	at com.microsoft.azure.vmagent.AzureVMManagementServiceDelegate.verifyVirtualMachineImage(AzureVMManagementServiceDelegate.java:2230)
	at com.microsoft.azure.vmagent.AzureVMManagementServiceDelegate.lambda$verifyTemplateAsync$1(AzureVMManagementServiceDelegate.java:2088)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

Note that **sshConfig** is null in the logs.
My guess is that this is caused by 
https://github.com/jenkinsci/azure-vm-agents-plugin/pull/357/commits/41a4f065c78952b0785efc5bec3f5c4de21eb039

**Comment by akomakom** [comment]
False alarm, I picked `Custom User Image` instead of `Custom Managed Image`

**Pull request merged**
