### PR TITLE
Fix a possible race condition and make sure the resource group has resources when trying to clean leaks

### PR DESCRIPTION
**Pull request by clguimanMSFT**

### CODE REVIEW

**Comment by mmitche** [comment]
@clguimanMSFT Where's the race?  Wouidn't the cleanup simply fail for a specific resource?

**Comment by clguimanMSFT** [comment]
the term 'race condition' is used loosely here :)
If the user would update the resource group name in the cloud definition we might end up looking inside an empty RG and we would log an exception. PriorityQueue throws an exception when the capacity is 0.

**Comment by mmitche** [comment]
Okay, so more on the priority queue side of things.  We already protect against exceptions in the actual cleanup area.

**Comment by mmitche** [comment]
+1

**Comment by clguimanMSFT** [comment]
I just want to avoid printing unnecessary exceptions in the logs

**Pull request merged**
