### PR TITLE
Add icon for new cloud layout

### PR DESCRIPTION
**Pull request by timja**
Requires https://github.com/jenkinsci/jenkins/pull/7658 to display anything.

image

### CODE REVIEW

**Comment by daniel-beck** [comment]
Any concerns about license?

**Comment by timja** [comment]
> Any concerns about license?

I think so, may need a difference icon.

**Comment by timja** [comment]
I've requested permission to use this from Microsoft.

**Comment by timja** [comment]
wasn't able to get anywhere so i'll close this

**Pull request closed without merging**
