### PR TITLE
JENKINS-64195 Make plugin work on Jenkins >=2.266

### PR DESCRIPTION
**Pull request by timja**
Requires https://github.com/jenkinsci/azure-commons-plugin/pull/51

I've included a couple of other fixes in here, https://issues.jenkins.io/browse/JENKINS-56077 and terminology updates, can be extracted to a different PR if required

### CODE REVIEW

**Review by fqueiruga — APPROVED** [review]
Haven' tested. Jelly code upgrades look good. Cannot evaluate the rest.

**Comment by timja** [comment]
Hi @xuzhang3 

Would you be able to take a look at this please?

Without this fix the Azure VM agents plugin UI is broken on versions newer than 2.263.

This is because of the tables to divs migration in Jenkins core for a better UI experience:
https://www.jenkins.io/blog/2020/11/10/major-changes-in-weekly-releases/#configuration-ui-tables-to-divs

All UI widgets were updated in core, but the azure-commons plugin had forked versions of two components that broke.

Please let me know if you have any questions, thanks.

_Note: This is using a pre-release build of azure-commmons, that one needs to be merged and released first_

**Review by oleg-nenashev — APPROVED** [review]
LGTM. A lot of changes for a single PR, but all of them look right

**Comment by xuzhang3** [comment]
LGTM

**Comment by timja** [comment]
https://github.com/jenkinsci/azure-commons-plugin/pull/51 Needs to be released first and then updating the version here

**Pull request merged**
